/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.mesosphere.usi

import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class DummySuite extends FunSuite {
  test("true is always true") {
    assert(true == true)
  }
}
