@startuml

object RunningPodSpec #Cyan {
  id
  runSpec
}

object RunSpec #Cyan {
  resourceRequirements
  commandInfo
  placementConstraints
  etc...
}

object ReservationSpec #Cyan {
  id
  agentId
  role
  resources
}

/' we'll have to store this, too, since Mesos expunges it. '/
object AgentInfo #LightGreen {
  id
  ip
  hostname
  faultDomain
  attributes
  maintenance
}

object ReservationRecord #Pink {
  id
  agentId
  resources
}

/' we have to store these because we cannot reliably recover it from Mesos under some situations, or it isn't available in Mesos at all... '/
object PodRecord #Pink {
  id
  launchedAt
  agentId
  unserviceable?
  -- reason (unhealthy | unreachable)
  -- since
}



object PodStatus {
  id
  status
  statusTimestamp
  agent: AgentInfo
  record: PodRecord
}

object ReservationStatus {
  id
  lastSeenAt
  agentInfo
  status
}

RunningPodSpec "1" -- "1" RunSpec
ReservationRecord "*" --> "1" AgentInfo
PodRecord "*" --> "1" AgentInfo
PodStatus "0..1" --> "0..1" PodRecord
PodStatus "*" --> "1" AgentInfo
ReservationStatus "0..1" --> "0..1" ReservationRecord

legend
  |= Legend|
  |<#Cyan> Input |
  |<#Pink> Persisted |
  |<#LightGreen> Cached (persisted) |
  |<#Yellow> Output |
endlegend

@enduml
