@startuml
Participant FrameworkState
Participant Scheduler
Participant SchedulerStorage
Participant Mesos
Participant Orchestrator

FrameworkState -> Scheduler: Launch Pod A#1
hnote over Scheduler
  No record exists for A#1; enqueued to launch.
  Revive for role sent to Mesos
end hnote

Scheduler -> SchedulerStorage: Revive
hnote over SchedulerStorage
  Nothing to store; just forward
end hnote

SchedulerStorage -> Mesos: Revive

Mesos -> Scheduler: Offer
hnote over Scheduler
  Matches offers against pending
  PodSpecs in a single, synchronous
  frame

  The offer matches
end hnote

Scheduler -> SchedulerStorage: Offer match result
hnote over SchedulerStorage
  Persist PodRecord with details of
  launch
end hnote

SchedulerStorage -> Mesos: Offer match result
SchedulerStorage -> Orchestrator: PodStatus A#1 launched


Mesos -> Scheduler: Task for Pod A#1 Running
Scheduler -> SchedulerStorage: PodStatus A#1 running
hnote over SchedulerStorage
  Nothing to persist
end hnote
SchedulerStorage -> Orchestrator: PodStatus A#1 running
@enduml
