# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloworld_pb2 as helloworld__pb2


class GreeterServiceStub(object):
  """#services
  //////////////////////////////////// The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/helloworld.GreeterService/SayHello',
        request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
        response_deserializer=helloworld__pb2.HelloReply.FromString,
        )
    self.ItKeepsTalking = channel.stream_unary(
        '/helloworld.GreeterService/ItKeepsTalking',
        request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
        response_deserializer=helloworld__pb2.HelloReply.FromString,
        )
    self.ItKeepsReplying = channel.unary_stream(
        '/helloworld.GreeterService/ItKeepsReplying',
        request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
        response_deserializer=helloworld__pb2.HelloReply.FromString,
        )
    self.StreamHellos = channel.stream_stream(
        '/helloworld.GreeterService/StreamHellos',
        request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
        response_deserializer=helloworld__pb2.HelloReply.FromString,
        )


class GreeterServiceServicer(object):
  """#services
  //////////////////////////////////// The greeting service definition.
  """

  def SayHello(self, request, context):
    """////////////////////
    Sends a greeting //
    //////*****/////////
    HELLO       //
    //////*****/////////
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ItKeepsTalking(self, request_iterator, context):
    """Comment spanning
    on several lines
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ItKeepsReplying(self, request, context):
    """
    C style comments
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamHellos(self, request_iterator, context):
    """C style comments
    on several lines
    with non-empty heading/trailing line 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=helloworld__pb2.HelloRequest.FromString,
          response_serializer=helloworld__pb2.HelloReply.SerializeToString,
      ),
      'ItKeepsTalking': grpc.stream_unary_rpc_method_handler(
          servicer.ItKeepsTalking,
          request_deserializer=helloworld__pb2.HelloRequest.FromString,
          response_serializer=helloworld__pb2.HelloReply.SerializeToString,
      ),
      'ItKeepsReplying': grpc.unary_stream_rpc_method_handler(
          servicer.ItKeepsReplying,
          request_deserializer=helloworld__pb2.HelloRequest.FromString,
          response_serializer=helloworld__pb2.HelloReply.SerializeToString,
      ),
      'StreamHellos': grpc.stream_stream_rpc_method_handler(
          servicer.StreamHellos,
          request_deserializer=helloworld__pb2.HelloRequest.FromString,
          response_serializer=helloworld__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.GreeterService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
