#!/usr/bin/env python3
import logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('usi')

import asyncio
import grpc
# from grpclib.client import Channel

# generated by protoc
from helloworld_pb2 import HelloRequest, HelloReply
from helloworld_pb2_grpc import GreeterServiceStub
# from helloworld_grpc import GreeterServiceStub

async def main():
    logger.info('create channel')
    channel = grpc.insecure_channel('127.0.0.1:8080')
    # channel = Channel('127.0.0.1', 8080)
    greeter = GreeterServiceStub(channel)

    logger.info('connected')

    # reply: HelloReply = await greeter.SayHello(HelloRequest(name='Dr. Strange'))
    reply = greeter.SayHello(HelloRequest(name='Dr. Strange'))
    logger.info('sent hello')

    print(reply.message)

    channel.close()


if __name__ == '__main__':
    asyncio.run(main())