/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.mesosphere.usi

import com.mesosphere.utils.UnitTest

class DummySuite extends UnitTest {
  "Hello world" should {
    "true is always true" in {
      assert(true == true)
    }
  }
}
